{% set name = "microsoft-aurora" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microsoft_aurora-{{ version }}.tar.gz
  sha256: 6ac3ce7fbe5382c7045143a9a090a69b2a50b5784ef6eedad9deda04d324cca5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - hatchling >=1.8.0
    - hatch-vcs
    - pip
    - python >=3.10
  run:
    - einops
    - huggingface_hub
    - numpy
    - python >=3.10
    - pytorch
    - scipy
    - timm ==0.6.13
  run_constrained:
    - aurora ==999  # avoid clobbering with https://github.com/simpeg/aurora

test:
  imports:
    - aurora
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Implementation of the Aurora model
  license: MIT
  license_file: LICENSE.txt
  home: https://microsoft.github.io/aurora/
  dev_url: https://github.com/microsoft/aurora
  doc_url: https://microsoft.github.io/aurora/api.html
  description: |
    Aurora is a machine learning model that can predict atmospheric variables, such as temperature.
    It is a foundation model, which means that it was first generally trained on a lot of data,
    and then can be adapted to specialised atmospheric forecasting tasks with relatively little data.
    Three such specialised versions are provided: one for medium-resolution weather prediction,
    one for high-resolution weather prediction, and one for air pollution prediction.

extra:
  recipe-maintainers:
    - awvwgk
